### ISSUE TITLE
Consider migration to laravel

### ISSUE THREAD

**Issue by TimZolleis** [DevicezApp/server#1]
For the purpose of the DeviceEZ server, i would suggest the migration to the laravel framework instead of codeigniter for a variety of reasons, but mainly because of what boilerplate and possibilities each framework brings with it. Ill focus on the pros of laravel here

**Utilities and framework design**
Laravel comes with a lot of built in utilities (for example manipulating strings, parsing and return requests, registering services (for example a mailable service with symfony mailer). Other benefits include a different approach on request validation & middleware, such as
- Chaining multiple middleware's and thus modifying the request
- Easy request validation with built in localization of error messages, complex validation possibilities (validating uniqueness against DB etc.) 
- Registering built-in and custom service providers with auto dependency injection

**ORM and Route-model binding**
Laravel provides a rather elevated ORM (eloquent) which does not require the codeigniter way of having two classes (model **and** entity). Relations are handled automatically aswell, with relationships being defined and queryable on the model via a function

**Job queuing**
For executing request asynchronously in a worker thread that does not block the main thread and thus may cause HTTP timeouts, laravel provides its queue system where (complex) jobs can be queued and executed in background with the possibility of providing complex documentation, error logging and delaying etc. 

*I see this feature mainly beneficial for a device management server, where jobs should **not** block the http session!*

**Frontend design**
Laravel provided various possibilities for adding a modern frontend-design to a php backend that does not require typeless HTML templating in PHP documents. You can either use JS for frontend or modern PHP templating with blade

*I can really recommend paring VueJS with inertia, which really improves page performance through partial prop loading, hydrating the page with JSON rather than downloading full HTML on reload* --> essentially a cool API where frontend and backend synchronize state without having to develop any API

**Popularity**
Since Laravel is well known and now V.10 coming, OSS contributions may be easier for people as they can get more resources and better documentation (I personally prefer Laravel Doc vs. Codeigniter doc - and migration isn't that much of a pain). 

Also the possibility of having sophisticated solutions for future problems is higher, as most laravel applications are more complex than codeigniter and thus those features may already exist

So finally I don't think that codeigniter is a bad framework, but for such a "complicated" use-case as a device management server, I do see laravel as a framework with solutions for more complex and advanced problems which fits better here.

**Comment by elektr0nisch** [comment]
Thank you for perfectly outlining the reasons why we should switch to Laravel! I did it!!

**Comment by TimZolleis** [comment]
Sui
